@description('Location for the vault.')
param location string

@description('Name of the Key Vault. Must be globally unique, 3-24 chars.')
param name string

@description('Tenant ID for RBAC.')
param tenantId string = subscription().tenantId

@description('GitHub OAuth App client secret.')
@secure()
param githubClientSecret string

@description('Auth.js session secret (npx auth secret).')
@secure()
param authSecret string

@description('32-byte base64 key for encrypting stored GitHub tokens at rest (openssl rand -base64 32).')
@secure()
param tokenEncryptionKey string

@description('Postgres admin password (generated by the deploy script).')
@secure()
param postgresAdminPassword string

// RBAC authorization (not legacy access policies) — grants are assigned
// separately (see main.bicep) to the Container App's managed identity,
// scoped to "Key Vault Secrets User" only (read secrets, nothing else).
resource vault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: name
  location: location
  properties: {
    tenantId: tenantId
    sku: {
      family: 'A'
      name: 'standard'
    }
    enableRbacAuthorization: true
    // Soft-delete is mandatory and free; purge protection is left off so a
    // `deploy.sh teardown` can fully remove the vault immediately instead
    // of leaving a 90-day soft-deleted vault blocking name reuse. Turn it
    // on (and accept that cost) once this holds anything beyond dev secrets.
    enableSoftDelete: true
    enablePurgeProtection: false
  }
}

resource secretGithubClientSecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: vault
  name: 'github-client-secret'
  properties: {
    value: githubClientSecret
  }
}

resource secretAuthSecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: vault
  name: 'auth-secret'
  properties: {
    value: authSecret
  }
}

resource secretTokenEncryptionKey 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: vault
  name: 'token-encryption-key'
  properties: {
    value: tokenEncryptionKey
  }
}

resource secretPostgresPassword 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: vault
  name: 'postgres-admin-password'
  properties: {
    value: postgresAdminPassword
  }
}

output vaultId string = vault.id
output vaultUri string = vault.properties.vaultUri
output githubClientSecretUri string = secretGithubClientSecret.properties.secretUri
output authSecretUri string = secretAuthSecret.properties.secretUri
output tokenEncryptionKeyUri string = secretTokenEncryptionKey.properties.secretUri
// A Key Vault secret *URI* (a pointer, resolved to the real value only at
// Container App runtime via managed identity), not the secret itself —
// safe to pass through deployment outputs/params despite the name.
#disable-next-line outputs-should-not-contain-secrets
output postgresAdminPasswordUri string = secretPostgresPassword.properties.secretUri
