package bicep

import (
	"fmt"
	"sort"
	"strings"

	"github.com/RuairiSpain/copilot-Web/x-foundry/internal/ids"
)

const header = "// Generated by x-foundry. Regenerate with `xfoundry generate` instead of editing this file.\n"

func (g *gen) tagsVar() string {
	merged := map[string]string{}
	for k, v := range g.n.Tags {
		merged[k] = v
	}
	merged["x-foundry-env"] = g.n.Environment
	return "var tags = " + tagsObject(merged) + "\n"
}

func (g *gen) locationParam() string {
	if loc := g.location(); loc != "" {
		return "param location string = " + str(loc) + "\n"
	}
	return "param location string\n"
}

const principalParams = `@description('Object ID of the identity running the deployment. It gets the Foundry User role on the Foundry resource. Leave empty to skip.')
param principalId string = ''

@allowed([
  'User'
  'Group'
  'ServicePrincipal'
])
param principalType string = 'User'
`

func (g *gen) mainBicep() string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("targetScope = 'subscription'\n\n")
	b.WriteString("@minLength(1)\n@maxLength(64)\n@description('Name of the environment. It is used in resource names and tags.')\nparam environmentName string\n\n")
	b.WriteString("@description('Primary location for all resources.')\n" + g.locationParam() + "\n")
	b.WriteString(principalParams + "\n")
	b.WriteString(g.tagsVar() + "\n")
	fmt.Fprintf(&b, "resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {\n  name: %s\n  location: location\n  tags: union(tags, { 'azd-env-name': environmentName, 'x-foundry-id': 'resource-group' })\n}\n\n", g.resourceGroupName())
	b.WriteString("module resources 'resources.bicep' = {\n  name: 'resources'\n  scope: rg\n  params: {\n    environmentName: environmentName\n    location: location\n    principalId: principalId\n    principalType: principalType\n  }\n}\n\n")
	b.WriteString("output AZURE_RESOURCE_GROUP string = rg.name\n")
	b.WriteString("output AZURE_AI_ACCOUNT_NAME string = resources.outputs.foundryAccountName\n")
	b.WriteString("output AZURE_AI_ENDPOINT string = resources.outputs.foundryEndpoint\n")
	b.WriteString("output AZURE_AI_PROJECTS array = resources.outputs.foundryProjects\n")
	return b.String()
}

func (g *gen) resourcesBicep() string {
	body := g.body.String()
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("param environmentName string\nparam location string\n\n")
	b.WriteString(principalParams + "\n")
	b.WriteString(g.tagsVar())
	b.WriteString("var token = toLower(uniqueString(subscription().id, environmentName, location))\n")
	fmt.Fprintf(&b, "var base = %s\n", str(g.prefix()))
	if strings.Contains(body, "baseCompact") {
		b.WriteString("var baseCompact = replace(base, '-', '')\n")
	}
	b.WriteString("\n")
	b.WriteString(body)
	fmt.Fprintf(&b, "output foundryAccountName string = %s.outputs.name\n", g.account)
	fmt.Fprintf(&b, "output foundryEndpoint string = %s.outputs.endpoint\n", g.account)
	var projects []string
	for _, node := range g.p.Nodes {
		if node.Kind == "foundry-project" && node.Scope != ids.HubScope {
			if s, ok := g.syms[node.ID]; ok {
				projects = append(projects, s+".outputs.name")
			}
		}
	}
	if len(projects) == 0 {
		b.WriteString("output foundryProjects array = []\n")
	} else {
		b.WriteString("output foundryProjects array = [\n")
		for _, p := range projects {
			fmt.Fprintf(&b, "  %s\n", p)
		}
		b.WriteString("]\n")
	}
	return b.String()
}

func (g *gen) parametersJSON() string {
	return `{
  "$schema": "https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "environmentName": {
      "value": "${AZURE_ENV_NAME}"
    },
    "location": {
      "value": "${AZURE_LOCATION}"
    },
    "principalId": {
      "value": "${AZURE_PRINCIPAL_ID}"
    }
  }
}
`
}

func (g *gen) readme(out *Output) string {
	n := g.n
	var b strings.Builder
	b.WriteString("# Generated infrastructure\n\n")
	b.WriteString("Generated by x-foundry from `azure.yaml`. Do not edit these files; change the YAML and regenerate.\n\n")
	fmt.Fprintf(&b, "* Environment: `%s`\n* Network: `%s` (%s)\n* Agent setup: `%s`\n\n", n.Environment, n.Network.Mode, n.Network.ModeSource, n.AgentSetup)
	b.WriteString("## Deploy\n\n```bash\naz deployment sub create --location <region> --template-file main.bicep \\\n  --parameters environmentName=<name> location=<region> principalId=$(az ad signed-in-user show --query id -o tsv)\n```\n\n")
	b.WriteString("With the Azure Developer CLI, `main.parameters.json` maps `AZURE_ENV_NAME`, `AZURE_LOCATION` and `AZURE_PRINCIPAL_ID`.\n\n")
	b.WriteString("## Resources\n\n| Node | Module |\n| --- | --- |\n")
	keys := make([]string, 0, len(g.syms))
	for id := range g.syms {
		keys = append(keys, id)
	}
	sort.Strings(keys)
	for _, id := range keys {
		fmt.Fprintf(&b, "| `%s` | `%s` |\n", id, g.syms[id])
	}
	b.WriteString("\nEvery resource carries the tags `x-foundry-env` and `x-foundry-id`, which later tooling uses to match Azure resources to this configuration.\n\n")
	if len(out.Diagnostics) > 0 {
		b.WriteString("## Warnings\n\n")
		for _, d := range out.Diagnostics {
			fmt.Fprintf(&b, "* `%s` %s: %s\n", d.Code, d.Path, d.Message)
		}
		b.WriteString("\n")
	}
	if len(out.Deferred) > 0 {
		b.WriteString("## Not generated yet\n\n")
		for _, d := range out.Deferred {
			fmt.Fprintf(&b, "* %s\n", d)
		}
		b.WriteString("\n")
	}
	b.WriteString("## Notes\n\n")
	b.WriteString("* Public and restricted modes leave service endpoints enabled (restricted adds the `allowedIps` rules); private mode disables them and uses private endpoints. Access is Microsoft Entra ID only unless a local-authentication setting is on.\n")
	b.WriteString("* Delete locks (`governance.resourceLocks`) must be removed before `azd down` or deleting the resource group.\n")
	b.WriteString("* Application Insights ingestion stays public: an Azure Monitor Private Link Scope is not generated.\n")
	b.WriteString("* Private DNS zone names assume the public Azure cloud.\n")
	b.WriteString("* If the resource group already exists, it must be in the same location as the `location` parameter.\n")
	return b.String()
}
