package bicep

import (
	"fmt"
	"sort"
	"strings"
)

const header = "// Generated by x-foundry. Regenerate with `xfoundry generate` instead of editing this file.\n"

func (g *gen) tagsVar() string {
	merged := map[string]string{}
	for k, v := range g.n.Tags {
		merged[k] = v
	}
	merged["x-foundry-env"] = g.n.Environment
	return "var tags = " + tagsObject(merged) + "\n"
}

func (g *gen) locationParam() string {
	if loc := g.location(); loc != "" {
		return "param location string = " + str(loc) + "\n"
	}
	return "param location string\n"
}

func (g *gen) mainBicep() string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("targetScope = 'subscription'\n\n")
	b.WriteString("@minLength(1)\n@maxLength(64)\n@description('Name of the environment. It is used in resource names and tags.')\nparam environmentName string\n\n")
	b.WriteString("@description('Primary location for all resources.')\n" + g.locationParam() + "\n")
	b.WriteString(g.tagsVar() + "\n")
	fmt.Fprintf(&b, "resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {\n  name: %s\n  location: location\n  tags: union(tags, { 'azd-env-name': environmentName, 'x-foundry-id': 'resource-group' })\n}\n\n", g.resourceGroupName())
	b.WriteString("module resources 'resources.bicep' = {\n  name: 'resources'\n  scope: rg\n  params: {\n    environmentName: environmentName\n    location: location\n  }\n}\n\n")
	b.WriteString("output AZURE_RESOURCE_GROUP string = rg.name\n")
	for _, o := range g.outputs {
		fmt.Fprintf(&b, "output %s string = resources.outputs.%s\n", o[0], o[0])
	}
	return b.String()
}

func (g *gen) resourcesBicep() string {
	body := g.body.String()
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("param environmentName string\nparam location string\n\n")
	b.WriteString(g.tagsVar())
	b.WriteString("var token = toLower(uniqueString(subscription().id, environmentName, location))\n")
	fmt.Fprintf(&b, "var base = %s\n", str(g.prefix()))
	if strings.Contains(body, "baseCompact") {
		b.WriteString("var baseCompact = replace(base, '-', '')\n")
	}
	b.WriteString("\n")
	b.WriteString(body)
	for _, o := range g.outputs {
		fmt.Fprintf(&b, "output %s string = %s\n", o[0], o[1])
	}
	return b.String()
}

func (g *gen) parametersJSON() string {
	return `{
  "$schema": "https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "environmentName": {
      "value": "${AZURE_ENV_NAME}"
    },
    "location": {
      "value": "${AZURE_LOCATION}"
    }
  }
}
`
}

func (g *gen) readme(out *Output) string {
	n := g.n
	var b strings.Builder
	b.WriteString("# Generated infrastructure\n\n")
	b.WriteString("Generated by x-foundry from `azure.yaml`. Do not edit these files; change the YAML and regenerate.\n\n")
	fmt.Fprintf(&b, "* Environment: `%s`\n* Network: `%s` (%s)\n* Agent setup: `%s`\n\n", n.Environment, n.Network.Mode, n.Network.ModeSource, n.AgentSetup)
	b.WriteString("## What this is, and what azd does\n\n")
	b.WriteString("This is the shared infrastructure around your Foundry project: network, private DNS, Storage, Cosmos DB, AI Search, Key Vault, monitoring, locks and operator roles. It does **not** create the Foundry resource, the project, model deployments, agents, toolboxes, connections, skills or routines: declare those as azd services (`azure.ai.project`, `azure.ai.agent`, `azure.ai.toolbox`, `azure.ai.connection`).\n\n")
	b.WriteString("## Deploy\n\nDeploy this first, then provision the azd project with the outputs below.\n\n```bash\naz deployment sub create --location <region> --template-file main.bicep \\\n  --parameters environmentName=<name> location=<region>\n```\n\n")
	b.WriteString("`main.parameters.json` maps `AZURE_ENV_NAME` and `AZURE_LOCATION` for azd.\n\n")
	if len(g.outputs) > 0 {
		b.WriteString("## Outputs for azd\n\nDeployment outputs, named so they can be set as azd environment values and referenced as `${NAME}` in `azure.yaml` (for example `network.peSubnet.vnet: ${VNET_RESOURCE_ID}` and `network.dns.resourceGroup: ${PRIVATE_DNS_RESOURCE_GROUP}` on the `azure.ai.project` service).\n\n| Output | Meaning |\n| --- | --- |\n")
		for _, o := range g.outputs {
			fmt.Fprintf(&b, "| `%s` | %s |\n", o[0], outputMeaning(o[0]))
		}
		b.WriteString("\n")
	}
	b.WriteString("## Resources\n\n| Node | Module |\n| --- | --- |\n")
	keys := make([]string, 0, len(g.syms))
	for id := range g.syms {
		keys = append(keys, id)
	}
	sort.Strings(keys)
	for _, id := range keys {
		fmt.Fprintf(&b, "| `%s` | `%s` |\n", id, g.syms[id])
	}
	b.WriteString("\nEvery resource carries the tags `x-foundry-env` and `x-foundry-id`, which later tooling uses to match Azure resources to this configuration.\n\n")
	if len(out.Diagnostics) > 0 {
		b.WriteString("## Warnings\n\n")
		for _, d := range out.Diagnostics {
			fmt.Fprintf(&b, "* `%s` %s: %s\n", d.Code, d.Path, d.Message)
		}
		b.WriteString("\n")
	}
	if len(out.Deferred) > 0 {
		b.WriteString("## Not generated yet\n\n")
		for _, d := range out.Deferred {
			fmt.Fprintf(&b, "* %s\n", d)
		}
		b.WriteString("\n")
	}
	b.WriteString("## Notes\n\n")
	b.WriteString("* Public and restricted modes leave service endpoints enabled (restricted adds the `allowedIps` rules); private mode disables them and uses private endpoints. Access is Microsoft Entra ID only unless a local-authentication setting is on.\n")
	b.WriteString("* Delete locks (`governance.resourceLocks`) must be removed before `azd down` or deleting the resource group.\n")
	b.WriteString("* Application Insights ingestion stays public: an Azure Monitor Private Link Scope is not generated.\n")
	b.WriteString("* Private DNS zone names assume the public Azure cloud.\n")
	b.WriteString("* If the resource group already exists, it must be in the same location as the `location` parameter.\n")
	return b.String()
}

func outputMeaning(name string) string {
	switch {
	case name == "VNET_RESOURCE_ID":
		return "the virtual network"
	case name == "PE_SUBNET_NAME":
		return "subnet for private endpoints"
	case name == "AGENT_SUBNET_NAME":
		return "subnet delegated to Microsoft.App/environments for the agent runtime"
	case name == "PRIVATE_DNS_RESOURCE_GROUP":
		return "resource group holding the private DNS zones (including the Foundry zones)"
	case name == "PRIVATE_DNS_SUBSCRIPTION_ID":
		return "subscription of those zones"
	case name == "STORAGE_ACCOUNT_RESOURCE_ID":
		return "Storage account"
	case name == "COSMOS_DB_RESOURCE_ID":
		return "Cosmos DB account"
	case name == "KEY_VAULT_RESOURCE_ID":
		return "Key Vault"
	case name == "LOG_ANALYTICS_WORKSPACE_ID":
		return "Log Analytics workspace"
	case name == "APPLICATIONINSIGHTS_RESOURCE_ID":
		return "Application Insights"
	case strings.HasPrefix(name, "AI_SEARCH_"):
		return "Azure AI Search service"
	}
	return ""
}
