package app

import (
	"bytes"
	"fmt"
	"html"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/ruairispain/copilot-web/foundry-doctor/internal/llm"
	"github.com/ruairispain/copilot-web/foundry-doctor/internal/report"
	"github.com/ruairispain/copilot-web/foundry-doctor/internal/report/common"
)

func appendRenderedNarrative(base []byte, format string, narrative *llm.Narrative, note string) []byte {
	switch format {
	case "html":
		return appendHTMLNarrative(base, narrative, note)
	case "markdown":
		return appendTextNarrative(base, markdownNarrative(narrative, note))
	default:
		return appendTextNarrative(base, consoleNarrative(narrative, note))
	}
}

func appendTextNarrative(base []byte, appendix string) []byte {
	if strings.TrimSpace(appendix) == "" {
		return base
	}
	var out bytes.Buffer
	out.Write(base)
	if len(base) > 0 && base[len(base)-1] != '\n' {
		out.WriteByte('\n')
	}
	if len(base) > 1 && base[len(base)-2] != '\n' {
		out.WriteByte('\n')
	}
	out.WriteString(appendix)
	return out.Bytes()
}

func markdownNarrative(narrative *llm.Narrative, note string) string {
	var b strings.Builder
	b.WriteString("## Advisory LLM narrative\n\n")
	note = sanitizeNarrativeText(note)
	if narrative != nil {
		provider := sanitizeNarrativeText(narrative.Metadata.Provider)
		model := sanitizeNarrativeText(narrative.Metadata.Model)
		deployment := sanitizeNarrativeText(narrative.Metadata.Deployment)
		promptVersion := sanitizeNarrativeText(narrative.Metadata.PromptVersion)
		fmt.Fprintf(&b, "> Generated by %s", common.Code(provider))
		if model != "" {
			fmt.Fprintf(&b, " model %s", common.Code(model))
		}
		if deployment != "" {
			fmt.Fprintf(&b, " deployment %s", common.Code(deployment))
		}
		if promptVersion != "" {
			fmt.Fprintf(&b, " using prompt %s", common.Code(promptVersion))
		}
		b.WriteString(". Advisory only; it cannot change findings, severity, or exit codes.\n\n")
		fmt.Fprintf(&b, "%s\n\n", common.EscapeMarkdown(sanitizeNarrativeText(narrative.Summary)))
		for _, section := range narrative.Sections {
			fmt.Fprintf(&b, "### %s\n\n%s\n\n", common.EscapeMarkdown(sanitizeNarrativeText(section.Heading)), common.EscapeMarkdown(sanitizeNarrativeText(section.Summary)))
			if len(section.RuleIDs) != 0 {
				ids := make([]string, 0, len(section.RuleIDs))
				for _, id := range section.RuleIDs {
					ids = append(ids, common.Code(sanitizeNarrativeText(id)))
				}
				fmt.Fprintf(&b, "- Rules: %s\n", strings.Join(ids, ", "))
			}
			if len(section.Actions) != 0 {
				b.WriteString("- Actions:\n")
				for _, action := range section.Actions {
					fmt.Fprintf(&b, "  - %s\n", common.EscapeMarkdown(sanitizeNarrativeText(action)))
				}
			}
			b.WriteString("\n")
		}
	}
	if note != "" {
		fmt.Fprintf(&b, "> %s\n", common.EscapeMarkdown(note))
	}
	return b.String()
}

func consoleNarrative(narrative *llm.Narrative, note string) string {
	var b strings.Builder
	b.WriteString("Advisory LLM narrative\n")
	b.WriteString("======================\n")
	note = sanitizeNarrativeText(note)
	if narrative != nil {
		provider := sanitizeNarrativeText(narrative.Metadata.Provider)
		model := sanitizeNarrativeText(narrative.Metadata.Model)
		deployment := sanitizeNarrativeText(narrative.Metadata.Deployment)
		promptVersion := sanitizeNarrativeText(narrative.Metadata.PromptVersion)
		fmt.Fprintf(&b, "Provider: %s\n", provider)
		if model != "" {
			fmt.Fprintf(&b, "Model: %s\n", model)
		}
		if deployment != "" {
			fmt.Fprintf(&b, "Deployment: %s\n", deployment)
		}
		if promptVersion != "" {
			fmt.Fprintf(&b, "Prompt version: %s\n", promptVersion)
		}
		b.WriteString("Advisory only; deterministic findings remain authoritative.\n\n")
		fmt.Fprintf(&b, "%s\n\n", sanitizeNarrativeText(narrative.Summary))
		for _, section := range narrative.Sections {
			fmt.Fprintf(&b, "%s\n%s\n", sanitizeNarrativeText(section.Heading), sanitizeNarrativeText(section.Summary))
			if len(section.RuleIDs) != 0 {
				ids := make([]string, 0, len(section.RuleIDs))
				for _, id := range section.RuleIDs {
					ids = append(ids, sanitizeNarrativeText(id))
				}
				fmt.Fprintf(&b, "Rules: %s\n", strings.Join(ids, ", "))
			}
			for _, action := range section.Actions {
				fmt.Fprintf(&b, "- %s\n", sanitizeNarrativeText(action))
			}
			b.WriteString("\n")
		}
	}
	if note != "" {
		fmt.Fprintf(&b, "Note: %s\n", note)
	}
	return b.String()
}

func appendHTMLNarrative(base []byte, narrative *llm.Narrative, note string) []byte {
	section := renderHTMLNarrative(narrative, note)
	if section == "" {
		return base
	}
	needle := []byte("</main>")
	if idx := bytes.LastIndex(base, needle); idx >= 0 {
		return append(append(append([]byte{}, base[:idx]...), []byte(section)...), base[idx:]...)
	}
	return append(base, []byte(section)...)
}

func renderHTMLNarrative(narrative *llm.Narrative, note string) string {
	if narrative == nil && strings.TrimSpace(note) == "" {
		return ""
	}
	note = sanitizeNarrativeText(note)
	var b strings.Builder
	b.WriteString(`<section aria-labelledby="llm-narrative">`)
	b.WriteString(`<h2 id="llm-narrative">Advisory LLM narrative</h2>`)
	if narrative != nil {
		provider := sanitizeNarrativeText(narrative.Metadata.Provider)
		model := sanitizeNarrativeText(narrative.Metadata.Model)
		deployment := sanitizeNarrativeText(narrative.Metadata.Deployment)
		promptVersion := sanitizeNarrativeText(narrative.Metadata.PromptVersion)
		b.WriteString(`<p>Generated advisory text. Deterministic findings remain authoritative.</p>`)
		fmt.Fprintf(&b, `<p><strong>Provider:</strong> %s`, html.EscapeString(provider))
		if model != "" {
			fmt.Fprintf(&b, ` <strong>Model:</strong> %s`, html.EscapeString(model))
		}
		if deployment != "" {
			fmt.Fprintf(&b, ` <strong>Deployment:</strong> %s`, html.EscapeString(deployment))
		}
		if promptVersion != "" {
			fmt.Fprintf(&b, ` <strong>Prompt version:</strong> %s`, html.EscapeString(promptVersion))
		}
		b.WriteString(`</p>`)
		fmt.Fprintf(&b, `<p>%s</p>`, html.EscapeString(sanitizeNarrativeText(narrative.Summary)))
		for _, section := range narrative.Sections {
			fmt.Fprintf(&b, `<article><h3>%s</h3><p>%s</p>`, html.EscapeString(sanitizeNarrativeText(section.Heading)), html.EscapeString(sanitizeNarrativeText(section.Summary)))
			if len(section.RuleIDs) != 0 {
				ids := make([]string, 0, len(section.RuleIDs))
				for _, id := range section.RuleIDs {
					ids = append(ids, sanitizeNarrativeText(id))
				}
				fmt.Fprintf(&b, `<p><strong>Rules:</strong> %s</p>`, html.EscapeString(strings.Join(ids, ", ")))
			}
			if len(section.Actions) != 0 {
				b.WriteString(`<ul>`)
				for _, action := range section.Actions {
					fmt.Fprintf(&b, `<li>%s</li>`, html.EscapeString(sanitizeNarrativeText(action)))
				}
				b.WriteString(`</ul>`)
			}
			b.WriteString(`</article>`)
		}
	}
	if note != "" {
		fmt.Fprintf(&b, `<p>%s</p>`, html.EscapeString(note))
	}
	b.WriteString(`</section>`)
	return b.String()
}

func allowedRuleIDs(ids []string) map[string]struct{} {
	out := make(map[string]struct{}, len(ids))
	for _, id := range ids {
		id = strings.TrimSpace(report.SafeRuleID(id))
		if id != "" && id != "unknown" {
			out[id] = struct{}{}
		}
	}
	return out
}

func sanitizeNarrativeText(s string) string {
	s = strings.ToValidUTF8(s, "\uFFFD")
	var b strings.Builder
	space := false
	for _, r := range s {
		if unicode.IsControl(r) || (r >= '\u2028' && r <= '\u202e') || (r >= '\u2066' && r <= '\u2069') || r == utf8.RuneError {
			if !space {
				b.WriteByte(' ')
			}
			space = true
			continue
		}
		if unicode.IsSpace(r) {
			if !space {
				b.WriteByte(' ')
			}
			space = true
			continue
		}
		space = false
		b.WriteRune(r)
	}
	return strings.TrimSpace(b.String())
}
