package catalog

import (
	"fmt"
	"sort"
	"strings"
)

// Markdown renders the catalogue as deterministic Markdown. Output depends only on rules.
func Markdown(rules []Rule) string {
	sorted := append([]Rule(nil), rules...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	var b strings.Builder
	b.WriteString("<!-- Code generated by `go run ./cmd/rulecatalog generate-docs`. DO NOT EDIT. -->\n\n")
	b.WriteString("# Foundry Doctor rule catalogue\n\n")
	fmt.Fprintf(&b, "%d rules. Generated from `rules/catalog/`.\n\n", len(sorted))

	counts := map[Status]int{}
	decisions := map[string]int{}
	for _, r := range sorted {
		counts[r.Status]++
		if r.Overlap.Decision != "" {
			decisions[r.Overlap.Decision]++
		}
	}
	b.WriteString("## Summary\n\n| Status | Rules |\n|---|---|\n")
	for _, s := range []Status{StatusProposed, StatusVerified, StatusProductOpinion, StatusImplemented, StatusDeprecated, StatusDropped} {
		if counts[s] > 0 {
			fmt.Fprintf(&b, "| %s | %d |\n", s, counts[s])
		}
	}
	b.WriteString("\n| Overlap decision | Rules |\n|---|---|\n")
	for _, d := range []string{"reuse", "wrap", "adapt", "native", "drop"} {
		if decisions[d] > 0 {
			fmt.Fprintf(&b, "| %s | %d |\n", d, decisions[d])
		}
	}

	group := ""
	for _, r := range sorted {
		if r.Group != group {
			group = r.Group
			fmt.Fprintf(&b, "\n## %s\n\n| Rule | Title | Phase | Status | Decision | dev/test/prod | Source |\n|---|---|---|---|---|---|---|\n", group)
		}
		sev := "-"
		if r.Severity.Dev != "" {
			sev = r.Severity.Dev + "/" + r.Severity.Test + "/" + r.Severity.Prod
		}
		src := "-"
		if len(r.Sources) > 0 {
			src = fmt.Sprintf("[link](%s) (%s)", r.Sources[0].URL, r.Sources[0].LastVerified)
		} else if r.Status == StatusProductOpinion {
			src = "product opinion"
		}
		dec := r.Overlap.Decision
		if dec == "" {
			dec = "-"
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s |\n", r.ID, esc(r.Title), strings.Join(r.Phases, "/"), r.Status, dec, sev, src)
	}
	return b.String()
}

func esc(s string) string { return strings.ReplaceAll(strings.ReplaceAll(s, "|", "\\|"), "\n", " ") }
