package catalog

import (
	"fmt"
	"slices"
	"strings"
)

// Markdown renders the catalogue as deterministic Markdown. Output depends only on rules.
func Markdown(rules []Rule) string {
	sorted := append([]Rule(nil), rules...)
	slices.SortFunc(sorted, func(a, b Rule) int { return strings.Compare(a.ID, b.ID) })

	var b strings.Builder
	b.WriteString("<!-- Code generated by `go run ./cmd/rulecatalog generate-docs`. DO NOT EDIT. -->\n\n")
	b.WriteString("# Foundry Doctor rule catalogue\n\n")
	fmt.Fprintf(&b, "%d rules. Generated from `rules/catalog/`.\n\n", len(sorted))

	counts := map[Status]int{}
	decisions := map[string]int{}
	for _, r := range sorted {
		counts[r.Status]++
		if r.Overlap.Decision != "" {
			decisions[r.Overlap.Decision]++
		}
	}
	b.WriteString("## Summary\n\n| Status | Rules |\n|---|---|\n")
	for _, s := range []Status{StatusProposed, StatusVerified, StatusProductOpinion, StatusImplemented, StatusDeprecated, StatusDropped} {
		if counts[s] > 0 {
			fmt.Fprintf(&b, "| %s | %d |\n", s, counts[s])
		}
	}
	b.WriteString("\n| Overlap decision | Rules |\n|---|---|\n")
	for _, d := range []string{"reuse", "wrap", "adapt", "native", "drop"} {
		if decisions[d] > 0 {
			fmt.Fprintf(&b, "| %s | %d |\n", d, decisions[d])
		}
	}

	mvp := []Rule{}
	for _, r := range sorted {
		if slices.Contains(r.Phases, "1") {
			mvp = append(mvp, r)
		}
	}
	fmt.Fprintf(&b, "\n## Phase 1 MVP set (%d rules)\n\nRules whose phases include 1, including those shared with a later phase. The PRD target is 35 to 40.\n\n", len(mvp))
	b.WriteString("| Rule | Title | Phases | Status | Decision |\n|---|---|---|---|---|\n")
	for _, r := range mvp {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", esc(r.ID), esc(r.Title), esc(strings.Join(r.Phases, "/")), esc(string(r.Status)), esc(dash(r.Overlap.Decision)))
	}

	group := ""
	for _, r := range sorted {
		if r.Group != group {
			group = r.Group
			fmt.Fprintf(&b, "\n## %s\n\n| Rule | Title | Phase | Status | Decision | dev/test/prod | Source |\n|---|---|---|---|---|---|---|\n", esc(group))
		}
		sev := "-"
		if r.Severity.Dev != "" {
			sev = r.Severity.Dev + "/" + r.Severity.Test + "/" + r.Severity.Prod
		}
		src := "-"
		if len(r.Sources) > 0 {
			src = fmt.Sprintf("[link](<%s>) (%s)", linkDestination(r.Sources[0].URL), esc(r.Sources[0].LastVerified))
		} else if r.Status == StatusProductOpinion {
			src = "product opinion"
		}
		dec := r.Overlap.Decision
		if dec == "" {
			dec = "-"
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s |\n", esc(r.ID), esc(r.Title), esc(strings.Join(r.Phases, "/")), esc(string(r.Status)), esc(dec), esc(sev), src)
	}
	return b.String()
}

func esc(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r == '&':
			b.WriteString("&amp;")
		case r == '<':
			b.WriteString("&lt;")
		case r == '>':
			b.WriteString("&gt;")
		case r == '|':
			b.WriteString("&#124;")
		case r == '`':
			b.WriteString("&#96;")
		case r == '\\':
			b.WriteString("&#92;")
		case unsafeFormatRune(r):
			b.WriteString("&#xfffd;")
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

func linkDestination(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r == '&':
			b.WriteString("&amp;")
		case unsafeFormatRune(r):
			b.WriteString("%EF%BF%BD")
		case r == '<', r == '>', r == '|', r == '`', r == '\\':
			for _, c := range []byte(string(r)) {
				fmt.Fprintf(&b, "%%%02X", c)
			}
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

func unsafeFormatRune(r rune) bool {
	return r < 0x20 || r >= 0x7f && r <= 0x9f ||
		r >= 0x202a && r <= 0x202e || r >= 0x2066 && r <= 0x2069 ||
		r == 0x200e || r == 0x200f || r == 0x061c
}
