package catalog

import (
	"fmt"
	"slices"
	"strings"
)

// OverlapMatrix renders docs/overlap-analysis.md: decision counts by group and one row per rule
// with the external rule IDs it maps to. Output depends only on rules.
func OverlapMatrix(rules []Rule) string {
	sorted := append([]Rule(nil), rules...)
	slices.SortFunc(sorted, func(a, b Rule) int { return strings.Compare(a.ID, b.ID) })

	decisions := []string{"reuse", "wrap", "adapt", "native", "drop"}
	groups := []string{}
	byGroup := map[string]map[string]int{}
	for _, r := range sorted {
		if _, ok := byGroup[r.Group]; !ok {
			byGroup[r.Group] = map[string]int{}
			groups = append(groups, r.Group)
		}
		byGroup[r.Group][r.Overlap.Decision]++
	}

	var b strings.Builder
	b.WriteString("<!-- Code generated by `go run ./cmd/rulecatalog generate-overlap`. DO NOT EDIT. -->\n\n")
	b.WriteString("# Overlap analysis\n\n")
	b.WriteString("How each Foundry Doctor rule relates to PSRule for Azure, Azure Policy, Defender for Cloud,\n")
	b.WriteString("Azure Advisor, the Bicep linter and Checkov. Generated from `rules/catalog/`. The reasoning behind\n")
	b.WriteString("each decision is in the rule's `overlap.rationale`; per-group research notes, unverified items and\n")
	b.WriteString("proposed new rules are in `docs/overlap/`.\n\n")
	b.WriteString("An empty Defender or Advisor cell means \"not verified\", not \"no equivalent\", unless the rule's own\n")
	b.WriteString("notes say otherwise. A rule with no decision yet is counted as unresearched.\n\n")

	b.WriteString("## Decisions by group\n\n| Group | reuse | wrap | adapt | native | drop | unresearched | total |\n|---|---|---|---|---|---|---|---|\n")
	totals := map[string]int{}
	cols := append(append([]string(nil), decisions...), "")
	for _, g := range groups {
		fmt.Fprintf(&b, "| %s", esc(g))
		n := 0
		for _, d := range cols {
			c := byGroup[g][d]
			totals[d] += c
			n += c
			fmt.Fprintf(&b, " | %d", c)
		}
		fmt.Fprintf(&b, " | %d |\n", n)
	}
	b.WriteString("| **all**")
	all := 0
	for _, d := range cols {
		all += totals[d]
		fmt.Fprintf(&b, " | %d", totals[d])
	}
	fmt.Fprintf(&b, " | %d |\n", all)

	b.WriteString("\n## Per-rule matrix\n\n| Rule | Decision | Coverage | PSRule | Azure Policy | Bicep linter | Checkov | Defender | Advisor |\n|---|---|---|---|---|---|---|---|---|\n")
	for _, r := range sorted {
		o := r.Overlap
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s | %s | %s |\n", esc(r.ID), esc(dash(o.Decision)), esc(dash(o.Coverage)),
			ids(o.PSRule), ids(o.AzurePolicy), ids(o.BicepLinter), ids(o.Checkov), ids(o.Defender), ids(o.Advisor))
	}
	return b.String()
}

func dash(s string) string {
	if s == "" {
		return "-"
	}
	return s
}

func ids(v []string) string {
	if len(v) == 0 {
		return "-"
	}
	out := make([]string, len(v))
	for i, s := range v {
		out[i] = "`" + esc(s) + "`"
	}
	return strings.Join(out, ", ")
}
