"""Model catalogs: `old` (Model Router 2025-11-18 pool minus deprecated models) and `new` (latest models).

Each catalog file (config/catalog_<compatibility>.json) is generated by scripts/build_catalogs.py.
"""
from __future__ import annotations

import hashlib
import json
import math
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .config import COMPATIBILITIES, ROUTING_MODES

APIS = ("openai_chat", "mai_chat", "anthropic_messages")
CAPABILITY_VALUES = ("yes", "no", "unknown")
EXCLUDED_LIFECYCLES = ("deprecated", "retired", "legacy")


@dataclass(frozen=True)
class ModelEntry:
    name: str
    deployment: str
    tier: int
    description: str
    provider: str
    api: str
    endpoint_path: str
    aliases: tuple[str, ...] = ()
    version: str = ""
    lifecycle: str = "unknown"
    retires: str | None = None
    in_model_router: bool = False
    context_tokens: int | None = None
    max_output_tokens: int | None = None
    capabilities: dict[str, str] = field(default_factory=dict)
    infrastructure: str = "azure"
    regions: dict[str, tuple[str, ...]] = field(default_factory=dict)

    def capability(self, name: str) -> str:
        return self.capabilities.get(name, "unknown")


@dataclass(frozen=True)
class RoutingMode:
    name: str
    instructions: str
    band_from: str
    band_share: float


class CatalogError(ValueError):
    pass


class Catalog:
    def __init__(self, compatibility: str, models: list[ModelEntry], modes: dict[str, RoutingMode],
                 default_mode: str, fingerprint: str = ""):
        self.compatibility = compatibility
        self.models = sorted(models, key=lambda m: m.tier)
        self.by_name = {m.name: m for m in self.models}
        self.modes = modes
        self.default_mode = default_mode
        self.fingerprint = fingerprint
        self._validate()

    @classmethod
    def load(cls, path: Path, deployment_overrides: dict[str, str] | None = None,
             default_mode: str | None = None) -> Catalog:
        raw_bytes = path.read_bytes()
        data = json.loads(raw_bytes)
        overrides = deployment_overrides or {}
        models = []
        for m in data["models"]:
            limits, hosting = m.get("limits") or {}, m.get("hosting") or {}
            models.append(ModelEntry(
                name=m["name"],
                deployment=overrides.get(m["name"], m.get("deployment") or m["name"]),
                tier=int(m["tier"]),
                description=m["description"].strip(),
                provider=m.get("provider", ""),
                api=m.get("api", "openai_chat"),
                endpoint_path=m.get("endpoint_path", "/openai/v1/chat/completions"),
                aliases=tuple(m.get("aliases", [])),
                version=str(m.get("version", "")),
                lifecycle=str(m.get("lifecycle", "unknown")).lower(),
                retires=m.get("retires"),
                in_model_router=bool(m.get("in_model_router")),
                context_tokens=limits.get("context_tokens"),
                max_output_tokens=limits.get("max_output_tokens"),
                capabilities=dict(m.get("capabilities") or {}),
                infrastructure=hosting.get("infrastructure", "azure"),
                regions={k: tuple(v) for k, v in (m.get("regions") or {}).items()},
            ))
        modes = {}
        for name, spec in data["routing_modes"].items():
            band = spec.get("price_band") or {"from": "cheapest", "share": 1.0}
            modes[name] = RoutingMode(name, spec["instructions"].strip(), band["from"], float(band["share"]))
        compatibility = data.get("compatibility") or path.stem.removeprefix("catalog_")
        return cls(compatibility, models, modes, default_mode or data.get("default_mode", "balanced"),
                   hashlib.sha256(raw_bytes).hexdigest())

    def _validate(self) -> None:
        names = [m.name for m in self.models]
        if len(set(names)) != len(names):
            raise CatalogError(f"{self.compatibility}: model names must be unique")
        tiers = [m.tier for m in self.models]
        if len(set(tiers)) != len(tiers):
            raise CatalogError(f"{self.compatibility}: model tiers must be unique so ranking ties break deterministically")
        for m in self.models:
            if not m.description:
                raise CatalogError(f"{m.name}: every model needs a description; Decision-1 reads it")
            if m.api not in APIS:
                raise CatalogError(f"{m.name}: api must be one of {APIS}")
            bad = {k: v for k, v in m.capabilities.items() if v not in CAPABILITY_VALUES}
            if bad:
                raise CatalogError(f"{m.name}: capability values must be yes/no/unknown, got {bad}")
        if set(self.modes) != set(ROUTING_MODES):
            raise CatalogError(f"{self.compatibility}: routing_modes must define exactly {ROUTING_MODES}")
        for mode in self.modes.values():
            if mode.band_from not in ("cheapest", "priciest") or not 0 < mode.band_share <= 1:
                raise CatalogError(f"routing mode '{mode.name}': price_band needs from=cheapest|priciest, 0<share<=1")
            if not mode.instructions:
                raise CatalogError(f"routing mode '{mode.name}' has no instructions")
        if self.default_mode not in self.modes:
            raise CatalogError(f"default_mode must be one of {ROUTING_MODES}")

    def price_band(self, mode: str, models: list[ModelEntry]) -> list[ModelEntry]:
        """The mode's share of `models` by price; never empty when `models` is not."""
        spec = self.modes[mode]
        ordered = sorted(models, key=lambda m: m.tier)
        count = max(1, math.ceil(len(ordered) * spec.band_share)) if ordered else 0
        return ordered[:count] if spec.band_from == "cheapest" else sorted(ordered[-count:], key=lambda m: m.tier)

    def criteria(self, candidates: list[ModelEntry]) -> dict[str, str]:
        """Option key -> description, with each model's price rank in the whole catalog."""
        total = len(self.models)
        rank = {m.name: i + 1 for i, m in enumerate(self.models)}
        return {
            m.name: f"{m.description} Price rank {rank[m.name]} of {total} in the pool (1 is cheapest)."
            for m in candidates
        }

    def resolve(self, served: str | None) -> str | None:
        """Map a model string returned by Foundry (often version-suffixed) to a catalog name."""
        if not served:
            return None
        value = served.strip().lower()
        for m in self.models:
            names = {m.name.lower(), m.deployment.lower(), *(a.lower() for a in m.aliases)}
            if value in names:
                return m.name
        for m in sorted(self.models, key=lambda e: len(e.name), reverse=True):
            if re.fullmatch(re.escape(m.name.lower()) + r"-\d{4}-\d{2}-\d{2}", value):
                return m.name
        return None

    def describe(self) -> dict[str, Any]:
        return {"compatibility": self.compatibility, "catalog_sha256": self.fingerprint,
                "models": [m.name for m in self.models], "default_mode": self.default_mode}


class Catalogs:
    """Both catalogs, selected per request by `compatibility`."""

    def __init__(self, catalogs: dict[str, Catalog], default: str):
        if default not in catalogs:
            raise CatalogError(f"ROUTER_COMPATIBILITY must be one of {sorted(catalogs)}")
        self.catalogs = catalogs
        self.default = default

    @classmethod
    def load(cls, directory: Path, default: str, deployment_overrides: dict[str, str] | None = None,
             default_mode: str | None = None) -> Catalogs:
        overrides = deployment_overrides or {}
        catalogs = {c: Catalog.load(directory / f"catalog_{c}.json", overrides, default_mode) for c in COMPATIBILITIES}
        known = set().union(*(c.by_name for c in catalogs.values()))
        unknown = set(overrides) - known
        if unknown:
            raise CatalogError(f"ROUTER_DEPLOYMENT_MAP names models in neither catalog: {sorted(unknown)}")
        return cls(catalogs, default)

    def get(self, compatibility: str | None) -> Catalog:
        key = compatibility or self.default
        if key not in self.catalogs:
            raise CatalogError(f"compatibility must be one of {sorted(self.catalogs)}")
        return self.catalogs[key]
