"""Port for per-agent metrics. Dimensions are bounded; identities are never recorded."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Protocol


class MetricsRecorder(Protocol):
    def request_completed(self, agent: str, outcome: str, duration_seconds: float) -> None: ...

    def queue_wait(self, agent: str, seconds: float) -> None: ...

    def queue_depth(self, agent: str, depth: int) -> None: ...

    def sessions(self, agent: str, counts: Mapping[tuple[str, str], int]) -> None:
        """Gauge of sessions by (platform status, local state)."""
        ...

    def session_created(self, agent: str) -> None: ...

    def session_reused(self, agent: str) -> None: ...

    def session_failed(self, agent: str) -> None: ...

    def session_deleted(self, agent: str, reason: str, outcome: str) -> None: ...

    def reconcile(self, agent: str, outcome: str, duration_seconds: float) -> None: ...

    def circuit_state(self, agent: str, state: str) -> None:
        """Gauge of the circuit breaker state: closed 0, half_open 1, open 2."""
        ...

    def circuit_transition(self, agent: str, to_state: str) -> None: ...

    def session_restored(self, agent: str) -> None: ...

    def quota_refused(self, agent: str, scope: str) -> None:
        """Foundry refused a session because a quota is full (``regional`` or ``session``)."""
        ...

    def session_evicted(self, agent: str) -> None:
        """A session was stopped to free quota. Its state is kept."""
        ...

    def sessions_counted(self, agent: str, count: int) -> None:
        """Gauge of the agent's sessions assumed to hold compute (the quota-relevant count)."""
        ...
